highlights: pygments
safe: true
lsi: false
exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'CNAME']
destination: _site

collections:
  2d:
    output: true
  3d:
    output: true

defaults:
  - scope:
      path: ""
      type: 2d
    values:
      layout: 2d
      show_date: false
  - scope:
      path: ""
      type: 3d
    values:
      layout: 3d
      show_date: true